name: pull-request
on:
  pull_request:
    branches:
      - master
jobs:    
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go 1.21
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.x'
      - name: Run tests
        run: go test ./...
      - name: Install and run
        run: |
          make install
          pulumictl convert-version -v 0.0.1+dev -l python
