name: prerelease
on:
  push:
    tags: [ "*.*.*-**" ] # Glob pattern matching valid prelease semver

jobs:    
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow clone
        run: git fetch --prune --unshallow
      - name: Install Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.x'
      - name: Goreleaser publish
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist --config=.goreleaser.prelease.yml
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
