name: prerelease
on:
  push:
    tags: [ "*.*.*-**" ] # Glob pattern matching valid prelease semver

jobs:    
  goreleaser:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Unshallow clone
        run: git fetch --prune --unshallow
      - name: Install Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Goreleaser publish
        uses: goreleaser/goreleaser-action@5742e2a039330cbb23ebf35f046f814d4c6ff811 # v5.1.0
        with:
          version: v1.26.2
          args: release --rm-dist --config=.goreleaser.prelease.yml
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
