permissions: write-all # Equivalent to default permissions plus id-token: write
env:
  ESC_ACTION_OIDC_AUTH: true
  ESC_ACTION_OIDC_ORGANIZATION: pulumi
  ESC_ACTION_OIDC_REQUESTED_TOKEN_TYPE: urn:pulumi:token-type:access_token:organization
  ESC_ACTION_ENVIRONMENT: imports/github-secrets
  ESC_ACTION_EXPORT_ENVIRONMENT_VARIABLES: false
name: release
on:
  push:
    tags: ["v*.*.*"]

jobs:
  goreleaser:
    runs-on: macos-latest
    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@v1
      - name: Checkout
        uses: actions/checkout@v4
      - name: Unshallow clone
        run: git fetch --prune --unshallow
      - name: Install Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Goreleaser publish
        uses: goreleaser/goreleaser-action@5742e2a039330cbb23ebf35f046f814d4c6ff811 # v5.1.0
        with:
          version: v1.26.2
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ steps.esc-secrets.outputs.PULUMI_BOT_TOKEN }}
      - name: Chocolatey Package Deployment
        run: |
          make install
          CURRENT_TAG=$(pulumictl get version --language generic -o)
          pulumictl create choco-deploy -a pulumictl ${CURRENT_TAG}
        env:
          GITHUB_TOKEN: ${{ steps.esc-secrets.outputs.PULUMI_BOT_TOKEN}}
